import { Component } from '@angular/core';
import { IPlant } from './plant.model';
import { AccountService } from '../account/account.service';

@Component({
  selector: 'app-plants',
  templateUrl: './plants.component.html',
  styleUrls: ['./plants.component.scss']
})

export class PlantsComponent { 
  plants: IPlant[];
  filter: string = '';
  myplants: IPlant[] = [];


    constructor(private accountservice: AccountService) {
  this.plants = [
    {
      id: 1,
      name: 'Rosmarin',
      latin: 'Rosmarinus officinalis',
      description: 'Ein mediterranes Küchenkraut mit intensivem Aroma, das oft zu Fleischgerichten passt.',
      imageName: 'rosmarin',
      category: 'Gartenpflanze',
      poisonous: false,
      edible: true,
      hardyInWinter: true,
      lightRequirement: 'Sonnig',
      leafColor: 'Grün',
      bloomingPeriod: 'Frühling bis Sommer',
      harvestMonths: [4, 5, 6, 7, 8, 9],
      fertilizingCycle: [3, 6],
      wateringCycle: [5, 6, 7, 8],
      soilType: 'sandig, trocken'
    },
    {
      id: 2,
      name: 'Erdbeere',
      latin: 'Fragariax ananassa',
      description: 'Eine süße rote Fruchtpflanze, beliebt in Desserts und als Snack.',
      imageName: 'erdbeere',
      category: 'Gartenpflanze',
      poisonous: false,
      edible: true,
      hardyInWinter: true,
      lightRequirement: 'Sonnig',
      leafColor: 'Grün',
      bloomingPeriod: 'Frühling',
      harvestMonths: [5, 6, 7],
      fertilizingCycle: [3, 5],
      wateringCycle: [4, 5, 6, 7],
      soilType: 'humusreich'
    },
    {
      id: 3,
      name: 'Monstera',
      latin: 'Monstera deliciosa',
      description: 'Eine tropische Zimmerpflanze mit charakteristischen, geschlitzten Blättern.',
      imageName: 'monstera',
      category: 'Zimmerpflanze',
      poisonous: true,
      edible: false,
      hardyInWinter: false,
      lightRequirement: 'halbschattig, hell, indirektes Licht',
      leafColor: 'Grün',
      bloomingPeriod: 'Selten',
      harvestMonths: [],
      fertilizingCycle: [4, 6, 8],
      wateringCycle: [3, 4, 5, 6, 7, 8, 9],
      soilType: 'torfhaltig, gut durchlässig'
    },
    {
      id: 4,
      name: 'Basilikum',
      latin: 'Ocimum basilicum',
      description: 'Ein aromatisches Kraut, besonders beliebt in der italienischen Küche.',
      imageName: 'basilikum',
      category: 'Gartenpflanze',
      poisonous: false,
      edible: true,
      hardyInWinter: false,
      lightRequirement: 'Sonnig',
      leafColor: 'Grün',
      bloomingPeriod: 'Sommer',
      harvestMonths: [6, 7, 8, 9],
      fertilizingCycle: [5, 7],
      wateringCycle: [5, 6, 7, 8],
      soilType: 'feucht, gut durchlässig'
    },
    {
      id: 5,
      name: 'Mirabelle',
      latin: 'Prunus domestica subsp. syriaca',
      description: 'Eine gelbe Pflaumenart mit süßem Geschmack, ideal für Marmeladen und Kuchen.',
      imageName: 'mirabelle',
      category: 'Gartenpflanze',
      poisonous: false,
      edible: true,
      hardyInWinter: true,
      lightRequirement: 'Sonnig bis halbschattig',
      leafColor: 'Grün',
      bloomingPeriod: 'Frühling',
      harvestMonths: [8],
      fertilizingCycle: [3, 6],
      wateringCycle: [4, 5, 6, 7, 8],
      soilType: 'nährstoffreich, gut durchlässig'
    },
    {
      id: 6,
      name: 'Japanischer Ahorn',
      latin: 'Acer palmatum',
      description: 'Ein dekorativer Laubbaum mit farbenfrohem Herbstlaub, beliebt in Ziergärten.',
      imageName: 'ahorn',
      category: 'Gartenpflanze',
      poisonous: false,
      edible: false,
      hardyInWinter: true,
      lightRequirement: 'Halbschattig',
      leafColor: 'Rot bis orange',
      bloomingPeriod: 'Frühling',
      harvestMonths: [],
      fertilizingCycle: [4],
      wateringCycle: [5, 6, 7],
      soilType: 'leicht sauer, humusreich'
    },
    {
      id: 7,
      name: 'Süßkirsche',
      latin: 'Prunus avium',
      description: 'Ein hoher Obstbaum mit süßen roten Früchten, beliebt bei Mensch und Tier.',
      imageName: 'suesskirsche',
      category: 'Gartenpflanze',
      poisonous: false,
      edible: true,
      hardyInWinter: true,
      lightRequirement: 'Sonnig',
      leafColor: 'Grün',
      bloomingPeriod: 'Frühling',
      harvestMonths: [6, 7],
      fertilizingCycle: [3, 6],
      wateringCycle: [4, 5, 6, 7],
      soilType: 'tiefgründig, durchlässig, kalkhaltig'
    },
    {
      id: 8,
      name: 'Forellenbegonie',
      latin: 'Begonia maculata',
      description: 'Eine exotische Zimmerpflanze mit auffällig gepunkteten Blättern.',
      imageName: 'forellenbegonie',
      category: 'Zimmerpflanze',
      poisonous: true,
      edible: false,
      hardyInWinter: false,
      lightRequirement: 'Helles, indirektes Licht',
      leafColor: 'Grün mit weißen Punkten',
      bloomingPeriod: 'Frühling bis Herbst',
      harvestMonths: [],
      fertilizingCycle: [4, 6, 8],
      wateringCycle: [4, 5, 6, 7, 8],
      soilType: 'luftig, leicht feucht'
    },
    {
      id: 9,
      name: 'Aloe Vera',
      latin: 'Aloe barbadensis miller',
      description: 'Eine sukkulente Heilpflanze, deren Gel oft für Hautpflege verwendet wird. Giftig für Haustiere.',
      imageName: 'aloevera',
      category: 'Zimmerpflanze',
      poisonous: true,
      edible: true,
      hardyInWinter: false,
      lightRequirement: 'Sonnig',
      leafColor: 'Grün',
      bloomingPeriod: 'Sommer',
      harvestMonths: [5, 6, 7, 8],
      fertilizingCycle: [4, 7],
      wateringCycle: [5, 6, 7, 8],
      soilType: 'sandig, gut drainiert, kaktuserde'
    },
    {
    id: 10,
    name: 'Gummibaum',
    latin: 'Ficus elastica',
    description: 'Eine pflegeleichte Zimmerpflanze mit großen, glänzenden Blättern.',
    imageName: 'gummibaum',
    category: 'Zimmerpflanze',
    poisonous: true,
    edible: false,
    hardyInWinter: false,
    lightRequirement: 'Helles, indirektes Licht, Halbschattig',
    leafColor: 'Dunkelgrün',
    bloomingPeriod: 'Selten',
    harvestMonths: [],
    fertilizingCycle: [4, 6, 8],
    wateringCycle: [4, 5, 6, 7, 8],
    soilType: 'locker, gut durchlässig'
  },
{
  id: 11,
  name: 'Glücksfeder',
  latin: 'Zamioculcas zamiifolia',
  description: 'Sehr robuste Pflanze, überlebt auch bei wenig Licht und Wasser.',
  imageName: 'glücksfeder',
  category: 'Zimmerpflanze',
  poisonous: true,
  edible: false,
  hardyInWinter: false,
  lightRequirement: 'Halbschattig bis schattig',
  leafColor: 'Dunkelgrün',
  bloomingPeriod: 'Selten',
  harvestMonths: [],
  fertilizingCycle: [4, 8],
  wateringCycle: [3, 5, 7],
  soilType: 'gut drainiert, kaktusähnlich'
},
{
  id: 12,
  name: 'Einblatt',
  latin: 'Spathiphyllum',
  description: 'Bekannt für ihre weißen Blüten und luftreinigende Wirkung.',
  imageName: 'einblatt',
  category: 'Zimmerpflanze',
  poisonous: true,
  edible: false,
  hardyInWinter: false,
  lightRequirement: 'Halbschattig',
  leafColor: 'Grün',
  bloomingPeriod: 'Frühling bis Herbst',
  harvestMonths: [],
  fertilizingCycle: [4, 6, 8],
  wateringCycle: [4, 5, 6, 7, 8],
  soilType: 'feucht, humos, gut durchlässig'
},
{
  id: 13,
  name: 'Fensterblatt',
  latin: 'Monstera adansonii',
  description: 'Verwandt mit der klassischen Monstera, aber mit kleinen, durchlöcherten Blättern.',
  imageName: 'fensterblatt',
  category: 'Zimmerpflanze',
  poisonous: true,
  edible: false,
  hardyInWinter: false,
  lightRequirement: 'Indirektes Licht,Halbschattig',
  leafColor: 'Grün',
  bloomingPeriod: 'Sehr selten',
  harvestMonths: [],
  fertilizingCycle: [4, 6, 8],
  wateringCycle: [3, 4, 5, 6, 7, 8, 9],
  soilType: 'torfhaltig, durchlässig'
},
{
  id: 14,
  name: 'Schwiegermutterzunge',
  latin: 'Sansevieria trifasciata',
  description: 'Extrem pflegeleicht, ideal für Anfänger. Benötigt kaum Wasser.',
  imageName: 'schwiegermutterzunge',
  category: 'Zimmerpflanze',
  poisonous: true,
  edible: false,
  hardyInWinter: false,
  lightRequirement: 'Sonnig, halbschattig, schattig',
  leafColor: 'Grün mit gelben Rändern',
  bloomingPeriod: 'Selten',
  harvestMonths: [],
  fertilizingCycle: [3, 7],
  wateringCycle: [4, 7],
  soilType: 'sandig, kaktusgeeignet'
},
{
  id: 17,
  name: 'Bogenhanf Zwergform',
  latin: 'Sansevieria cylindrica',
  description: 'Sehr pflegeleicht, verträgt auch längere Trockenzeiten.',
  imageName: 'bogenhanf_cylindrica',
  category: 'Zimmerpflanze',
  poisonous: true,
  edible: false,
  hardyInWinter: false,
  lightRequirement: 'Sonnig bis schattig',
  leafColor: 'Graugrün',
  bloomingPeriod: 'Sehr selten',
  harvestMonths: [],
  fertilizingCycle: [3, 8],
  wateringCycle: [14, 21],
  soilType: 'kaktusgeeignet, gut durchlässig'
},
{
  id: 18,
  name: 'Zamioculcas',
  latin: 'Zamioculcas zamiifolia',
  description: 'Extrem genügsam, ideal für wenig Licht.',
  imageName: 'zamioculcas',
  category: 'Zimmerpflanze',
  poisonous: true,
  edible: false,
  hardyInWinter: false,
  lightRequirement: 'Schattig',
  leafColor: 'Dunkelgrün, glänzend',
  bloomingPeriod: 'Selten',
  harvestMonths: [],
  fertilizingCycle: [6, 10],
  wateringCycle: [10, 20],
  soilType: 'gut durchlässig, leicht sandig'
},
{
  id: 19,
  name: 'Grünlilie',
  latin: 'Chlorophytum comosum',
  description: 'Anspruchslos, bildet viele Ableger, gut zur Luftreinigung.',
  imageName: 'gruenlilie',
  category: 'Zimmerpflanze',
  poisonous: false,
  edible: false,
  hardyInWinter: false,
  lightRequirement: 'Sonnig bis halbschattig',
  leafColor: 'Grün mit weißem Rand',
  bloomingPeriod: 'Frühling bis Herbst',
  harvestMonths: [],
  fertilizingCycle: [4, 8],
  wateringCycle: [3, 6],
  soilType: 'lockere Blumenerde'
},
{
  id: 21,
  name: 'Fensterblatt Mini',
  latin: 'Monstera adansonii',
  description: 'Kompaktere Monstera-Art mit typischen Lochblättern.',
  imageName: 'monstera_adansonii',
  category: 'Zimmerpflanze',
  poisonous: true,
  edible: false,
  hardyInWinter: false,
  lightRequirement: 'Sonnig bis halbschattig',
  leafColor: 'Grün',
  bloomingPeriod: 'Selten',
  harvestMonths: [],
  fertilizingCycle: [4, 7],
  wateringCycle: [5, 9],
  soilType: 'locker, humos'
},
{
  id: 22,
  name: 'Kentia Palme',
  latin: 'Howea forsteriana',
  description: 'Elegante Zimmerpalme, sehr robust und langlebig.',
  imageName: 'kentia_palme',
  category: 'Zimmerpflanze',
  poisonous: false,
  edible: false,
  hardyInWinter: false,
  lightRequirement: 'Hell bis halbschattig',
  leafColor: 'Grün',
  bloomingPeriod: 'Frühjahr, jedoch selten im Haus',
  harvestMonths: [],
  fertilizingCycle: [4, 8],
  wateringCycle: [5, 10],
  soilType: 'palmengeeignete Erde'
},
{
  id: 23,
  name: 'Farn Schwertfarn',
  latin: 'Nephrolepis exaltata',
  description: 'Beliebter Farn mit buschigem Wuchs, liebt hohe Luftfeuchte.',
  imageName: 'schwertfarn',
  category: 'Zimmerpflanze',
  poisonous: false,
  edible: false,
  hardyInWinter: false,
  lightRequirement: 'Halbschattig',
  leafColor: 'Hellgrün',
  bloomingPeriod: 'Nicht relevant (sporentragend)',
  harvestMonths: [],
  fertilizingCycle: [4, 8],
  wateringCycle: [2, 5],
  soilType: 'torfhaltig, locker'
},
{
  id: 24,
  name: 'Flamingoblume',
  latin: 'Anthurium andraeanum',
  description: 'Dekorative Blüten, benötigt hohe Luftfeuchtigkeit.',
  imageName: 'flamingoblume',
  category: 'Zimmerpflanze',
  poisonous: true,
  edible: false,
  hardyInWinter: false,
  lightRequirement: 'Hell, indirektes Licht',
  leafColor: 'Dunkelgrün, glänzend',
  bloomingPeriod: 'Ganzjährig bei guter Pflege',
  harvestMonths: [],
  fertilizingCycle: [4, 7],
  wateringCycle: [4, 7],
  soilType: 'orchideengeeignet, luftig'
},
{
  id: 25,
  name: 'Ficus Benjamini',
  latin: 'Ficus benjamina',
  description: 'Beliebter Zimmerbaum mit feinem Blattwerk, benötigt konstante Bedingungen.',
  imageName: 'ficusbenjamini',
  category: 'Zimmerpflanze',
  poisonous: true,
  edible: false,
  hardyInWinter: false,
  lightRequirement: 'Hell, indirektes Licht, Schattig',
  leafColor: 'Dunkelgrün',
  bloomingPeriod: 'Sehr selten in Innenräumen',
  harvestMonths: [],
  fertilizingCycle: [4, 8],
  wateringCycle:[5, 9],
  soilType: 'locker, humos'
},
{
  id: 26,
  name: 'Korbmarante',
  latin: 'Calathea orbifolia',
  description: 'Dekorative Blätter, benötigt hohe Luftfeuchtigkeit und warmes Klima.',
  imageName: 'korbmarante',
  category: 'Zimmerpflanze',
  poisonous: false,
  edible: false,
  hardyInWinter: false,
  lightRequirement: 'Halbschattig',
  leafColor: 'Grün mit silbernen Streifen',
  bloomingPeriod: 'Selten',
  harvestMonths: [],
  fertilizingCycle: [4, 7],
  wateringCycle: [3, 5],
  soilType: 'torfhaltig, locker'
},
{
  id: 27,
  name: 'Pfeilblatt',
  latin: 'Alocasia amazonica',
  description: 'Exotische Pflanze mit kontrastreichen, pfeilförmigen Blättern.',
  imageName: 'pfeilblatt',
  category: 'Zimmerpflanze',
  poisonous: true,
  edible: false,
  hardyInWinter: false,
  lightRequirement: 'Halbschattig',
  leafColor: 'Dunkelgrün mit weißen Adern',
  bloomingPeriod: 'Selten',
  harvestMonths: [],
  fertilizingCycle: [4, 7],
  wateringCycle: [4, 7],
  soilType: 'leicht sauer, humos'
},
{
  id: 28,
  name: 'Zwergpfeffer',
  latin: 'Peperomia obtusifolia',
  description: 'Kompakte, pflegeleichte Zimmerpflanze, ideal für kleine Räume.',
  imageName: 'zwergpfeffer',
  category: 'Zimmerpflanze',
  poisonous: true,
  edible: false,
  hardyInWinter: false,
  lightRequirement: 'Hell bis halbschattig',
  leafColor: 'Dunkelgrün, fleischig',
  bloomingPeriod: 'Sommer',
  harvestMonths: [],
  fertilizingCycle: [5, 9],
  wateringCycle: [5, 10],
  soilType: 'locker, leicht sandig'
},
{
  id: 29,
  name: 'Flamingo-Lilie Rosa',
  latin: 'Anthurium clarinervium',
  description: 'Auffallende Herzblätter mit hellen Blattadern.',
  imageName: 'anthurium_clarinervium',
  category: 'Zimmerpflanze',
  poisonous: true,
  edible: false,
  hardyInWinter: false,
  lightRequirement: 'Halbschattig',
  leafColor: 'Dunkelgrün mit weißen Adern',
  bloomingPeriod: 'Ganzjährig möglich',
  harvestMonths: [],
  fertilizingCycle: [4, 7],
  wateringCycle: [4, 7] ,
  soilType: 'luftig, orchideengeeignet'
},
{
  id: 30,
  name: 'Birkenfeige Mini',
  latin: 'Ficus microcarpa Ginseng',
  description: 'Bonsai-ähnliche Zimmerpflanze mit dicken Wurzeln.',
  imageName: 'ficus_ginseng',
  category: 'Zimmerpflanze',
  poisonous: true,
  edible: false,
  hardyInWinter: false,
  lightRequirement: 'Halbschattig',
  leafColor: 'Grün',
  bloomingPeriod: 'Sehr selten',
  harvestMonths: [],
  fertilizingCycle: [4, 7],
  wateringCycle: [4, 8],
  soilType: 'bonsaigeeignet'
},
{
  id: 31,
  name: 'Schefflera',
  latin: 'Schefflera arboricola',
  description: 'Robuste Strahlenaralie, gut geeignet für helle Räume.',
  imageName: 'schefflera',
  category: 'Zimmerpflanze',
  poisonous: true,
  edible: false,
  hardyInWinter: false,
  lightRequirement: 'Hell bis halbschattig',
  leafColor: 'Grün',
  bloomingPeriod: 'Selten',
  harvestMonths: [],
  fertilizingCycle: [4, 8],
  wateringCycle: [5, 9],
  soilType: 'lockere Blumenerde'
},
{
  id: 33,
  name: 'Jadebaum',
  latin: 'Crassula ovata',
  description: 'Sehr langlebige Sukkulente, ideal für sonnige Fensterplätze.',
  imageName: 'crassula_ovata',
  category: 'Zimmerpflanze',
  poisonous: true,
  edible: false,
  hardyInWinter: false,
  lightRequirement: 'Sonnig',
  leafColor: 'Hellgrün, fleischig',
  bloomingPeriod: 'Winter bis Frühling',
  harvestMonths: [],
  fertilizingCycle: [4, 8],
  wateringCycle: [10, 20],
  soilType: 'sukkulentengeeignet'
},
{
  id: 34,
  name: 'Usambaraveilchen',
  latin: 'Saintpaulia ionantha',
  description: 'Beliebte Blühpflanze für Innenräume, kompakt und farbenfroh.',
  imageName: 'usambaraveilchen',
  category: 'Zimmerpflanze',
  poisonous: true,
  edible: false,
  hardyInWinter: false,
  lightRequirement: 'Halbschattig',
  leafColor: 'Dunkelgrün, weich',
  bloomingPeriod: 'Ganzjährig bei guter Pflege',
  harvestMonths: [],
  fertilizingCycle: [3, 7],
  wateringCycle: [3, 6],
  soilType: 'leicht sauer, locker'
}

  ];
}

 

    getFilterProducts() {
      const filtered = this.filter === ''
      ? this.plants
      : this.plants.filter((plant) => plant.category === this.filter);

      return filtered.sort((a, b) => a.name.localeCompare(b.name));
    }

    addToAccount(plant: IPlant) {
      console.log('addToAccount wurde aufgerufen mit Pflanze:', plant);
      if(!this.myplants.some(p => plant))
        this.accountservice.add(plant);
    }

  
}
